/**
 * Types for mobile sensor data logging feature
 * Used for recording GPS + accelerometer data to generate power vs speed charts
 */

/**
 * Raw sensor sample captured during recording
 */
export interface SensorSample {
  timestamp: number; // ms since recording start

  // Accelerometer data (m/s²)
  accelX: number;
  accelY: number;
  accelZ: number;

  // GPS data
  gpsSpeed: number | null; // m/s (null if unavailable)
  gpsAccuracy: number | null; // meters
  latitude: number | null;
  longitude: number | null;
}

/**
 * Calibration data computed at recording start
 * Used to transform device coordinates to kart coordinates
 */
export interface CalibrationData {
  // Gravity vector in device coordinates (m/s²)
  gravityVector: [number, number, number];

  // Forward direction in device coordinates (unit vector)
  forwardVector: [number, number, number];

  // Right direction in device coordinates (unit vector)
  rightVector: [number, number, number];

  // Up direction in device coordinates (unit vector)
  upVector: [number, number, number];

  // 3x3 rotation matrix: device coords → kart coords
  // Columns are [forward, right, up] in device coordinates
  rotationMatrix: [
    [number, number, number],
    [number, number, number],
    [number, number, number]
  ];

  // Quality score (0-1) indicating calibration confidence
  qualityScore: number;

  // Timestamp when calibration was completed
  calibratedAt: number;
}

/**
 * Processed power/speed data point for charting
 */
export interface SpeedPowerPoint {
  speedKmh: number; // Center of speed bin (km/h)
  speedMs: number; // Center of speed bin (m/s)
  avgPower: number; // Average power (CV)
  avgPowerWatts: number; // Average power (W)
  avgForwardAccel: number; // Average forward acceleration (m/s²)
  sampleCount: number; // Number of samples in this bin
}

/**
 * Complete sensor session stored in IndexedDB
 */
export interface SensorSession {
  id?: number; // Auto-generated by IndexedDB

  // Session metadata
  name: string;
  createdAt: Date;
  updatedAt: Date;

  // Recording parameters
  kartWeight: number; // kg (including driver)
  recordingDuration: number; // ms

  // Calibration data used for this session
  calibration: CalibrationData;

  // Raw recorded samples
  samples: SensorSample[];

  // Processed power curve data
  speedPowerCurve: SpeedPowerPoint[];

  // Statistics
  statistics: SensorSessionStatistics;
}

/**
 * Summary statistics for a sensor session
 */
export interface SensorSessionStatistics {
  peakPower: number; // CV
  peakPowerSpeed: number; // km/h at peak power
  maxSpeed: number; // km/h
  maxAcceleration: number; // G-force
  maxDeceleration: number; // G-force (positive value)
  totalSamples: number;
  validSpeedSamples: number; // Samples with GPS speed
}

/**
 * Recording state machine states
 */
export type RecordingState =
  | 'idle'
  | 'requesting-permissions'
  | 'calibrating-gravity'
  | 'calibrating-forward'
  | 'recording'
  | 'paused'
  | 'stopped'
  | 'processing'
  | 'error';

/**
 * Calibration step for UI display
 */
export type CalibrationStep = 'gravity' | 'forward';

/**
 * Sensor permissions status
 */
export interface SensorPermissions {
  motion: 'granted' | 'denied' | 'prompt' | 'not-supported';
  geolocation: 'granted' | 'denied' | 'prompt' | 'not-supported';
}
